name: latex_table
description: A Dart library to parse an object structure to LaTeX source code for a simple table.
version: 1.0.1

topics: 
  - latex
  - parsing
  - table
  - library
  - scientific

repository: https://github.com/centaurus22/latex-table

environment:
  sdk: ^3.10.7

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

funding: 
  - https://www.paypal.com/paypalme/klausthorres